export const SAVE_CLOUD_CONSULTATION = 'SAVE_CLOUD_CONSULTATION'
export const SAVE_CLOUD_CONSULTATION_AUTH = 'SAVE_CLOUD_CONSULTATION_AUTH'
export const SAVE_PARTNERS_CONSULTATION = 'SAVE_PARTNERS_CONSULTATION'
export const SAVE_PARTNERS_CONSULTATION_AUTH = 'SAVE_PARTNERS_CONSULTATION_AUTH'
