<template>
  <div class="loadingio-spinner-dual-ring-hl0qo0hd7tr">
    <div class="ldio-1bdwsuwbfuu">
      <div></div>
      <div><div></div></div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
@keyframes ldio-1bdwsuwbfuu {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-1bdwsuwbfuu div {
  box-sizing: border-box !important;
}
.ldio-1bdwsuwbfuu > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #d20121 transparent #d20121 transparent;
  animation: ldio-1bdwsuwbfuu 1s linear infinite;
}
.ldio-1bdwsuwbfuu > div:nth-child(2) {
  border-color: transparent;
}
.ldio-1bdwsuwbfuu > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-1bdwsuwbfuu > div:nth-child(2) div:before,
.ldio-1bdwsuwbfuu > div:nth-child(2) div:after {
  content: '';
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #d20121;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #d20121;
}
.ldio-1bdwsuwbfuu > div:nth-child(2) div:after {
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #d20121;
}
.loadingio-spinner-dual-ring-hl0qo0hd7tr {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-1bdwsuwbfuu {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-1bdwsuwbfuu div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
