export const HOME = 'home'
export const SYNERGY = 'synergy'
export const LINE_UP = 'line-up'
export const OBJECT = 'object'
export const ITEM = 'item'
export const RANKING = 'ranking'
export const ACP = 'acp'
